# File names for when kamran is kicked
kick_kamran_audio_files:
  - "kamran1.mp3"
  - "kamran2.mp3"
  - "kamran3.mp3"
  - "kamran4.mp3"
  - "kamran5.mp3"
  - "kamran6.mp3"
  - "kamran7.mp3"
  - "kamran8.mp3"
  - "kamran9.mp3"
  - "kamran10.mp3"
  - "kamran11.mp3"
  - "kamran12.mp3"

# File names for when caller is kicked
kick_caller_audio_file: "khande_kiri.mp3"

# File names for when kamran is not in channel
celebration_audio_file: "dead.mp3"

# Kamran's unique id
kamran_uid: 336082523010629632

# Increase in chance to kick caller each time kamran is kicked (between 0 & 1)
caller_kick_chance_step: 0.10

# Name of the channel bot will listen to commands and send responses
bot_commands_channel: "bot-commands"

# MongoDB configs
# Password should be put in .env file
mongo_address: "localhost"
mongo_username: "AoKBot"
mongo_db_name: "AttackOnKamran"
